Repository puppetlabs/puppetlabs-scheduled_task, pull requests merged in 2020-08, with the labels that each got.

#153 Update README.md
  README.md
Labels: maintenance

#154 pdksync - (IAC-973) - Update travis/appveyor to run on new default branch `main`
  .travis.yml
  Rakefile
  appveyor.yml
  metadata.json
Labels: feature

#158 (MODULES-10783) Add back empty? check for `datetime_string` value
  lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
Labels: bugfix

#159 (maint) pin bolt version to 2.23.0
  Gemfile
Labels: maintenance

#160 (IAC-1100) Release MergeBack v2.2.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#161 (bugfix) - fix `disable_time_zone_synchronization` so that it correctly disables functionality when set to true
  lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
Labels: bugfix
