Repository puppetlabs/puppetlabs-scheduled_task, pull requests merged in 2020-12, with the labels that each got.

#167 (maint) Port module to Cloud CI platform
  .github/workflows/nightly.yml
  .github/workflows/pr_test.yml
  .github/workflows/release.yml
  .github/workflows/weekly.yml
  .rubocop.yml
  .sync.yml
  lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
  lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
  lib/puppet/type/scheduled_task.rb
  lib/puppet_x/puppetlabs/scheduled_task/error.rb
  lib/puppet_x/puppetlabs/scheduled_task/task.rb
  lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
  metadata.json
  spec/acceptance/should_create_task_spec.rb
  spec/acceptance/should_destroy_spec.rb
  spec/integration/puppet_x/puppetlabs/scheduled_task/task_spec.rb
  spec/legacy_taskscheduler.rb
  spec/spec_helper_acceptance_local.rb
  spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb
  spec/unit/puppet/type/scheduled_task_spec.rb
  spec/unit/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb
Labels: maintenance

#168 (maint) Fix Windows OS casing in metadata.json
  metadata.json
Labels: maintenance

#169 pdksync - (feat) - Bump Puppet boundary
  metadata.json
Labels: feature

#172 (IAC-1009) - Removal of Inappropriate Terminology
  CONTRIBUTING.md
  README.md
Labels: maintenance

#173 Release version 2.3.0
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance

#176 (MAINT) Remove errant comma from provision.yaml
  provision.yaml
Labels: maintenance

#175 (MODULES-10893) Fix Last Day Of Month Trigger
  README.md
  lib/puppet/type/scheduled_task.rb
  lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
  spec/acceptance/should_create_task_spec.rb
  spec/unit/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb
Labels: bugfix

#177 Release version 2.3.1
  CHANGELOG.md
  REFERENCE.md
  metadata.json
Labels: maintenance
