Repository puppetlabs/puppetlabs-scheduled_task, pull requests merged in 2020-07, with the labels that each got.

#145 (IAC-918) - `disable_time_zone_synchronization` function implemented
  lib/puppet/type/scheduled_task.rb
  lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
  spec/acceptance/should_create_task_spec.rb
Labels: enhancement

#147 Merge back for release v2.1.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#149 (maint) - docs fix
  REFERENCE.md
Labels: maintenance

#150 (IAC-732) - implement `Run only when user is logged on
  REFERENCE.md
  lib/puppet/type/scheduled_task.rb
  lib/puppet_x/puppetlabs/scheduled_task/task.rb
  spec/acceptance/should_create_task_spec.rb
Labels: feature
